### PR TITLE
Use rails 3.0.3

### PR DESCRIPTION
**Pull request by oscardelben**
People should be upgrading to the latest 3.0.3 instead of the beta3.

### CODE REVIEW

**Comment by miloops** [comment]
+1, just wrote the same patch and then found this pull request already existed.

**Comment by pallan** [comment]
This patch should probably be updated for 3.0.4

**Comment by oscardelben** [comment]
I'm not even sure they're ever going to accept it.

**Comment by pallan** [comment]
Unfortunately, based on the pile of pull requests you my be right.

**Comment by radar** [comment]
Thanks, I've applied this patch and bumped it to using 3.0.6.

**Pull request merged**
